airline/airline/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("flights/", include("flights.urls")),
    path("user/", include("user.urls"))
]

airline/flights/urls.py
from django.urls import path
from . import views

# 在urls.py 我们定义了app_name 之后refer url name都要加: 如：
# <li><a href="{% url 'flights:flight' flight.id %}">Flight {{ flight.id }}</a>: {{ flight.origin }} to {{ flight.destination }}</li>
app_name="flights"
urlpatterns=[
    path('', views.index, name="index"),
    path('<int:flight_id>',views.flight,name="flight"),
    path('<int:flight_id>/book',views.book,name="book")
]

airline/user/urls.py
from django.urls import path
from . import views

# 在urls.py 我们定义了app_name 之后refer url name都要加: 如：
# <li><a href="{% url 'flights:flight' flight.id %}">Flight {{ flight.id }}</a>: {{ flight.origin }} to {{ flight.destination }}</li>
app_name="user"
urlpatterns=[
    path('', views.index, name="index"),
    path('login',views.login_view,name="login"),
    path('logout',views.logout_view,name="logout")
]

airline/flights/models.py
from django.db import models

# Create your models here.
class Airport(models.Model):
    code = models.CharField(max_length=3)
    city = models.CharField(max_length=64)

    def __str__(self):
        return f"{self.city} ({self.code})"

class Flight(models.Model):
    origin = models.ForeignKey(Airport, on_delete=models.CASCADE, related_name="departures")
    destination = models.ForeignKey(Airport, on_delete=models.CASCADE, related_name="arrivals")
    duration = models.IntegerField()

    def __str__(self):
        return f"{self.id}: {self.origin} to {self.destination}"

class Passenger(models.Model):
    first=models.CharField(max_length=64)
    last=models.CharField(max_length=64)
    flights=models.ManyToManyField(Flight,blank=True,related_name="passengers")

    def __str__(self):
        return f"{self.first} {self.last}"

airline/user/models.py
from django.db import models

# Create your models here.

airline/flights/views.py
from django.shortcuts import render
from .models import Flight, Airport,Passenger
from django.http import HttpResponseRedirect
from django.urls import reverse

# Create your views here.

def index(request):
    return render(request, "flights/index.html", {
        "flights": Flight.objects.all()
    })

def flight(request,flight_id):
    flight=Flight.objects.get(id=flight_id)
    return render(request,"flights/flight.html",{
        "flight":flight,
        "passengers":flight.passengers.all(),
        "non_passengers":Passenger.objects.exclude(flights=flight).all()
    })

def book(request, flight_id):

    # For a post request, add a new flight
    if request.method == "POST":

        # Accessing the flight
        flight = Flight.objects.get(pk=flight_id)

        # Finding the passenger id from the submitted form data
        passenger_id = int(request.POST["passenger"])

        # Finding the passenger based on the id
        passenger = Passenger.objects.get(pk=passenger_id)

        # Add passenger to the flight
        passenger.flights.add(flight)

        # Redirect user to flight page
        return HttpResponseRedirect(reverse("flights:flight", args=(flight.id,)))

airline/user/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.urls import reverse



# Create your views here.
def index(request):
    # If no user is signed in, return to login page:
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("user:login"))
    return render(request, "user/user.html")

def login_view(request):
    if request.method == "POST":
        # Accessing username and password from form data
        username = request.POST["username"]
        password = request.POST["password"]

        # Check if username and password are correct, returning User object if so
        user = authenticate(request, username=username, password=password)

        # If user object is returned, log in and route to index page:
        if user:
            login(request, user)
            return HttpResponseRedirect(reverse("flights:index"))
        # Otherwise, return login page again with new context
        else:
            return render(request, "user/login.html", {
                "message": "Invalid Credentials"
            })
    return render(request, "user/login.html")

def logout_view(request):
    logout(request)
    return render(request, "user/login.html", {
                "message": "Logged Out"
            })

airline/flights/templates/flights/flight.html
{% extends "flights/layout.html" %}

{% block body %}
    <h1>Flight {{flight.id}}</h1>
    <ul>
        
        <li>Origin: {{ flight.origin }}</li>
        <li>Destination: {{ flight.destination }}</li>
        <li>Duration: {{ flight.duration }} mins</li>
        
    </ul>

    <h2>Passengers</h2>
    <ul>
        {% for passenger in passengers %}
            <li>{{ passenger }} </li>
        {% empty %}
            <li>No passengers. </li>
        {% endfor %}  
    </ul>

    <h2>
    <form action="{% url 'flights:book' flight.id %}" method="post">
        {% csrf_token %}
        <select name="passenger" id="">
            {% for passenger in non_passengers %}
                <option value="{{ passenger.id }}">{{ passenger }}</option>
            {% endfor %}
        </select>
        <input type="submit">
    </form>

    </h2>
    <!--  这里我们要'flights:index' 因为在urls.py 我们定义了app_name 之后refer url name都要加:-->
    <a href="{% url 'flights:index'%}">All flights</a> 
{% endblock %}

airline/flights/templates/flights/index.html
{% extends "flights/layout.html" %}

{% block body %}
    <h1>Flights:</h1>
    <ul>
        {% for flight in flights %}
            <!-- 这里我们要'flights:flight' 因为在urls.py 我们定义了app_name 之后refer url name都要加:-->
            <li><a href="{% url 'flights:flight' flight.id %}">Flight {{ flight.id }}</a>: {{ flight.origin }} to {{ flight.destination }}</li>
        {% endfor %}
    </ul>
{% endblock %}

airline/flights/templates/flights/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Flights</title>
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>

airline/user/templates/user/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>User</title>
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>

airline/user/templates/user/login.html
{% extends "user/layout.html" %}

{% block body %}
    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'user:login' %}" method="post">
        {% csrf_token %}
        <input type="text", name="username", placeholder="Username">
        <input type="password", name="password", placeholder="Password">
        <input type="submit", value="Login">
    </form>
{% endblock %}

airline/user/templates/user/user.html
{% extends "user/layout.html" %}

{% block body %}
    <h1>Welcome, {{ request.user.first_name }}</h1>
    <ul>
        <li>Username: {{ request.user.username }}</li>
        <li>Email: {{ request.user.email }}</li>
    </ul>

    <a href="{% url 'user:logout' %}">Log Out</a>
{% endblock %}